# Generated by Django 4.0.4 on 2023-10-31 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_sild',
            new_name='is_sold',
        ),
    ]
