# Generated by Django 4.0.4 on 2023-11-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_is_sild_item_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
